# Use postgres/example user/password credentials
version: '3.1'

services:

  grpc:
    container_name: grpc-server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5500:5432"
